#!/usr/bin/env python3

from os import getenv
from copy import deepcopy
from threading import Thread
from time import sleep
import logging
import sys
import kubernetes

# flake8: noqa

_API = None
_API_networking = None
MAX_COUNT_ERROR = 5
CURRENT_COUNT_ERROR = 0
SLEEP_TIME_COEFFICIENT = 2
CM_NAMESPACE = "kube-system"
OUT_OF_CLUSTER = getenv("OUT_OF_CLUSTER", "True")
DEBUG_KUBECONFIG = getenv("DEBUG_KUBECONFIG", "~/.kube/config_main")
DEBUG_CONTEXT = getenv("DEBUG_CONTEXT", "dev")
FORCE_NGINX_INGRESS = getenv("FORCE_NGINX_INGRESS", "False")

logger = logging.getLogger()
logger.setLevel(logging.getLevelName(getenv("LOGLEVEL", "INFO").upper()))
logger.addHandler(logging.StreamHandler(sys.stdout))


def process(event):
    global _API
    if event['object'].spec.type == "LoadBalancer" and (event['type'] == "ADDED" or event['type'] == "MODIFIED"):
        if event['object'].metadata.annotations:
            if event['object'].metadata.annotations.get('platrorm/autogenerated'):
                return
            if event['object'].metadata.annotations.get('platrorm/external-load-balancing'):
                services_num = int(event['object'].metadata.annotations.get('platrorm/external-load-balancing'))
                source_object = event['object']

                for i in range(services_num):
                    new_object = deepcopy(source_object)
                    new_object.metadata.name = source_object.metadata.name + "-" + str(i)
                    try:
                        new_object.metadata.annotations.pop("platrorm/external-load-balancing")
                    except KeyError:
                        logger.info("This is a new autogenerated svc")
                    new_object.metadata.annotations["platrorm/autogenerated"] = "true"
                    spec = new_object.spec.to_dict()
                    spec.pop("cluster_ip")
                    spec.pop("cluster_i_ps")
                    new_object.spec = spec
                    metadata = new_object.metadata.to_dict()
                    metadata.pop("creation_timestamp")
                    metadata.pop("resource_version")
                    metadata.pop("uid")
                    new_object.metadata = metadata
                    _API.create_namespaced_service(
                        namespace=source_object.metadata.namespace,
                        body=new_object)
                    metadata = {
                        "metadata": {
                            "annotations": {
                                "platrorm/autogenerated": "true"
                            }
                        }
                    }
                    _API.patch_namespaced_service(
                        name=event['object'].metadata.name,
                        namespace=event['object'].metadata.namespace,
                        body=metadata)

    if event['object'].spec.type == "LoadBalancer" and (event['type'] == "ADDED" or event['type'] == "MODIFIED"):
        if event['object'].metadata.annotations:
            if (event['object'].metadata.annotations.get("lbipam.cilium.io/sharing-key") !=
                    event['object'].metadata.namespace):
                metadata = {
                    "metadata": {
                        "annotations": {
                            "lbipam.cilium.io/sharing-key": "{}".format(event['object'].metadata.namespace),
                        },
                    }
                }
                try:
                    _API.patch_namespaced_service(
                        name=event['object'].metadata.name,
                        namespace=event['object'].metadata.namespace,
                        body=metadata)
                    logger.info("Patched service: %s %s %s %s %s", event['object'].metadata.name, " ",
                                event['object'].metadata.namespace,
                                " ",
                                event['object'].spec.type)
                except kubernetes.client.exceptions.ApiException as e:
                    if e.status == 403:
                        logger.info("Something is blocking service patch, admin action is necessary")
                    else:
                        logger.info(e)
        else:
            metadata = {
                "metadata": {
                    "annotations": {
                        "lbipam.cilium.io/sharing-key": "{}".format(event['object'].metadata.namespace),
                    }
                }
            }
            try:
                _API.patch_namespaced_service(
                    name=event['object'].metadata.name,
                    namespace=event['object'].metadata.namespace,
                    body=metadata)
                logger.info("Patched service: %s %s %s %s %s", event['object'].metadata.name, " ",
                            event['object'].metadata.namespace,
                            " ",
                            event['object'].spec.type)
            except kubernetes.client.exceptions.ApiException as e:
                if e.status == 403:
                    logger.info("Something is blocking service patch, admin action is necessary")
                else:
                    logger.info(e)


def thread_ingress_patcher():
    global _API_networking
    global CURRENT_COUNT_ERROR
    w = kubernetes.watch.Watch()
    for event in w.stream(_API_networking.list_ingress_for_all_namespaces, timeout_seconds=0):
        logger.info("Event: %s %s", event['type'], event['object'].metadata.name)
        process_ingress(event)
        CURRENT_COUNT_ERROR = 0


def thread_svc_patcher():
    global _API_networking
    global CURRENT_COUNT_ERROR
    w = kubernetes.watch.Watch()
    for event in w.stream(_API.list_service_for_all_namespaces, field_selector='spec.type=LoadBalancer',
                          timeout_seconds=0):
        logger.info("Event: %s %s", event['type'], event['object'].metadata.name)
        process(event)
        CURRENT_COUNT_ERROR = 0


def process_ingress(event):
    global _API_networking
    spec = {
        "spec": {
            "ingressClassName": "nginx"
        }
    }
    if event['type'] == "ADDED" or event['type'] == "MODIFIED":
        if event['object'].spec.ingress_class_name:
            if not event['object'].spec.ingress_class_name == "nginx":
                if FORCE_NGINX_INGRESS == "True":
                    _API_networking.patch_namespaced_ingress(
                        name=event['object'].metadata.name,
                        namespace=event['object'].metadata.namespace,
                        body=spec)
                    logger.info("Patched ingress: %s %s %s", event['object'].metadata.name,
                                event['object'].metadata.namespace,
                                event['object'].spec.ingress_class_name)
        else:
            _API_networking.patch_namespaced_ingress(
                name=event['object'].metadata.name,
                namespace=event['object'].metadata.namespace,
                body=spec)
            logger.info("Patched ingress: %s %s %s", event['object'].metadata.name, event['object'].metadata.namespace,
                        event['object'].spec.ingress_class_name)


def init_kubernetes_and_api():
    global _API
    global _API_networking
    configuration = kubernetes.client.Configuration()
    if OUT_OF_CLUSTER == "True":
        kubernetes.config.load_kube_config(DEBUG_KUBECONFIG, DEBUG_CONTEXT, configuration)
    else:
        kubernetes.config.load_incluster_config(configuration)
    _API = kubernetes.client.CoreV1Api(
        kubernetes.client.ApiClient(configuration))
    _API_networking = kubernetes.client.NetworkingV1Api(
        kubernetes.client.ApiClient(configuration))


def run_lb_gen_svc():
    global CURRENT_COUNT_ERROR
    try:
        init_kubernetes_and_api()
        logger.info("Api initialised, starting main cycle")
        thread_event = Thread(target=thread_svc_patcher)
        thread_loop = Thread(target=thread_ingress_patcher)
    except Exception as e:
        logger.error("Error in initialization %s", e)
    thread_loop.start()
    thread_event.start()

    while CURRENT_COUNT_ERROR <= MAX_COUNT_ERROR:
        SLEEP_TIME = min(SLEEP_TIME_COEFFICIENT ** CURRENT_COUNT_ERROR, 180)
        try:
            if not thread_event.is_alive():
                thread_event = Thread(target=thread_svc_patcher)
                thread_event.start()
            if not thread_loop.is_alive():
                thread_loop = Thread(target=thread_ingress_patcher)
                thread_loop.start()
            sleep(1)
        except (kubernetes.client.exceptions.ApiException, kubernetes.config.config_exception.ConfigException) as exc:
            logger.exception("Errors in gen_svc: %s.\n Count of error...%s(max count 5), Scripts wait %s sec: ",
                             exc, CURRENT_COUNT_ERROR, SLEEP_TIME)
            CURRENT_COUNT_ERROR += 1
            sleep(SLEEP_TIME)
    logger.error("Can't run gen_svc...Exit")
    sys.exit(1)


if __name__ == "__main__":
    run_lb_gen_svc()
